apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-{{.Values.application.id}}
---

apiVersion: apps/v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{.Release.Name}}-{{.Values.application.id}}
  namespace: {{.Values.application.namespace}}
  labels:
    app: {{.Release.Name}}-{{.Values.application.id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Values.application.id}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.application.id}}
        version: v0.0.1
    spec:
      containers:
      - name: {{.Release.Name}}-{{.Values.application.id}}
        image: hortonworks/dlm-app:1.4.0.0-4
        ports:
        - containerPort: 9011
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{.Values.application.id}}
  namespace: {{.Values.application.namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9011
    name: http
  selector:
    app: {{.Release.Name}}-{{.Values.application.id}}
