#Add Ingress Definition here.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}-dlm-add-dlm-app-ingress
  namespace: {{.Values.application.namespace}}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{.Values.application.host}}
    http:
      paths:
      - path: /dlm
        backend:
          serviceName: {{.Release.Name}}-dlm-add-dlm-app
          servicePort: http
