#Add Ingress Definition here.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}--{{.Values.application.id}}-ingress
  namespace: {{.Values.application.namespace}}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{.Values.application.host}}
    http:
      paths:
      - path: /dwx-sql
        backend:
          serviceName: {{.Release.Name}}-{{.Values.application.id}}
          servicePort: http
