apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-{{.Values.application.id}}
---

apiVersion: apps/v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{.Release.Name}}-{{.Values.application.id}}
  namespace: dataplane
  labels:
    app: {{.Release.Name}}-{{.Values.application.id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Values.application.id}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.application.id}}
        version: v0.0.1
    spec:
      containers:
      - name: {{.Release.Name}}-{{.Values.application.id}}
        image: hortonworks/dps-demo-app:0.0.1-dev
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{.Values.application.id}}
  namespace: dataplane
spec:
  ports:
  - name: http
    targetPort: 3000
    port: 80
  selector:
    app: {{.Release.Name}}-{{.Values.application.id}}